package llmbench

import (
	"fmt"
	"io"
	"math"
	"strings"
	"text/template"
)

// TexEscape escapes special LaTeX characters.
func TexEscape(s string) string {
	r := strings.NewReplacer(
		"_", `\_`,
		"%", `\%`,
		"&", `\&`,
		"#", `\#`,
		"$", `\$`,
		"{", `\{`,
		"}", `\}`,
		"~", `\textasciitilde{}`,
	)
	return r.Replace(s)
}

// ShortModelTexName shortens a provider/model string for captions (e.g. ollama/qwen2.5:3b-instruct).
func ShortModelTexName(s string) string {
	parts := strings.SplitN(s, "/", 2)
	name := parts[len(parts)-1]
	name = strings.ReplaceAll(name, ":latest", "")
	return TexEscape(name)
}

// LevelTagShort maps full level names to short labels (L1, L2, L3).
func LevelTagShort(s string) string {
	switch s {
	case "L1-diagnostic":
		return "L1"
	case "L2-repair":
		return "L2"
	case "L3-multi-step":
		return "L3"
	}
	return s
}

// FmtSci formats very small p-values in scientific notation for LaTeX.
func FmtSci(v float64) string {
	if v == 0 {
		return "$< 10^{-15}$"
	}
	if v >= 0.001 {
		return fmt.Sprintf("%.4f", v)
	}
	exp := int(math.Floor(math.Log10(math.Abs(v))))
	mantissa := v / math.Pow(10, float64(exp))
	return fmt.Sprintf("$%.2f{\\times}10^{%d}$", mantissa, exp)
}

// FmtDelta formats a signed delta for tables.
func FmtDelta(v float64) string {
	if v > 0 {
		return fmt.Sprintf("+%.4f", v)
	}
	if v < 0 {
		return fmt.Sprintf("%.4f", v)
	}
	return "0"
}

// FmtDeltaPct formats a delta as a percentage (ESR scale 0–1).
func FmtDeltaPct(v float64) string {
	pct := v * 100
	if pct > 0 {
		return fmt.Sprintf("+%.1f", pct)
	}
	if pct < 0 {
		return fmt.Sprintf("%.1f", pct)
	}
	return "0.0"
}

// FmtSig maps significance strings to LaTeX macro calls.
func FmtSig(s string) string {
	switch s {
	case "***":
		return `\sigHigh{***}`
	case "**":
		return `\sigMed{**}`
	case "*":
		return `\sigLow{*}`
	case "n.s.":
		return `n.s.`
	default:
		return "---"
	}
}

// MetricIsHolmTested returns true if the metric row used Holm–Bonferroni correction.
func MetricIsHolmTested(m MetricComparison) bool {
	return m.CorrectionMethod != "" && m.CorrectionMethod != "n/a"
}

// FilterHolmTestedMetrics keeps only statistically tested aggregate rows.
func FilterHolmTestedMetrics(ms []MetricComparison) []MetricComparison {
	var out []MetricComparison
	for _, m := range ms {
		if MetricIsHolmTested(m) {
			out = append(out, m)
		}
	}
	return out
}

// FilterScalarMetrics keeps descriptive-only rows (no per-run vector).
func FilterScalarMetrics(ms []MetricComparison) []MetricComparison {
	var out []MetricComparison
	for _, m := range ms {
		if !MetricIsHolmTested(m) {
			out = append(out, m)
		}
	}
	return out
}

// CountTaskComparisonDelta counts wins/ties/losses for model A vs B (dir: 1, 0, -1 by Delta sign).
func CountTaskComparisonDelta(tc []TaskComparison, dir int) int {
	n := 0
	for _, t := range tc {
		switch {
		case dir > 0 && t.Delta > 0:
			n++
		case dir < 0 && t.Delta < 0:
			n++
		case dir == 0 && t.Delta == 0:
			n++
		}
	}
	return n
}

// CompareLatexTemplate is the embedded table set for a CompareReport.
const CompareLatexTemplate = `%% ==========================================================================
%% Auto-generated by llmbench/cmd/latex — do not edit manually.
%% Generated: {{.GeneratedAt}}
%% Model A: {{esc .ModelA}}
%% Model B: {{esc .ModelB}}
%% ==========================================================================
%%
%% Required packages (add to your preamble):
%%   \usepackage{booktabs}
%%   \usepackage{multirow}
%%   \usepackage{xcolor}
%%   \usepackage{siunitx}
%%
%% Significance color commands (add to preamble):
%%   \newcommand{\sigHigh}[1]{\textcolor{green!60!black}{\textbf{#1}}}
%%   \newcommand{\sigMed}[1]{\textcolor{green!60!black}{\textbf{#1}}}
%%   \newcommand{\sigLow}[1]{\textcolor{orange!80!black}{#1}}
%%


%% ==========================================================================
%% TABLE 1: Aggregate Metrics — Tested (Wilcoxon + Holm-Bonferroni)
%% ==========================================================================
\begin{table*}[t]
\centering
\caption{Aggregate benchmark results comparing {{shortName .ModelA}} (A) and {{shortName .ModelB}} (B) across 60 Kubernetes diagnostic tasks. Metrics marked with $\uparrow$ are higher-is-better; $\downarrow$ lower-is-better. Statistical significance assessed via Wilcoxon rank-sum test with Holm--Bonferroni correction ($m={{len (tested .Aggregate)}}$). Effect size: rank-biserial~$r$.}
\label{tab:aggregate}
\small
\begin{tabular}{@{}llrrrcrrr@{}}
\toprule
Metric & Dir. & \multicolumn{1}{c}{A} & \multicolumn{1}{c}{B} & $\Delta$ & $p_{\text{corr}}$ & Sig. & $r$ & Effect \\
\midrule
{{- range tested .Aggregate}}
{{.Name}} & {{if .HigherIsBetter}}$\uparrow${{else}}$\downarrow${{end}} & {{f4 .ValueA}} & {{f4 .ValueB}} & {{delta .Delta}} & {{sci .PValueCorrected}} & {{sig .Significance}} & {{f3 .EffectSize}} & {{.EffectLabel}} \\
{{- end}}
\bottomrule
\end{tabular}
\end{table*}


%% ==========================================================================
%% TABLE 2: Scalar Metrics (no per-run vectors — descriptive only)
%% ==========================================================================
\begin{table}[t]
\centering
\caption{Supplementary scalar metrics. CES$=-1$ denotes zero-cost local deployment (undefined ratio). These metrics lack per-run distributions and are reported descriptively without statistical testing.}
\label{tab:scalars}
\small
\begin{tabular}{@{}llrrl@{}}
\toprule
Metric & Dir. & \multicolumn{1}{c}{A} & \multicolumn{1}{c}{B} & $\Delta$ \\
\midrule
{{- range scalars .Aggregate}}
{{- if and (ne .Name "CES") (ne .Name "CCR") (ne .Name "CTR")}}
{{.Name}} & {{if .HigherIsBetter}}$\uparrow${{else}}$\downarrow${{end}} & {{f4 .ValueA}} & {{f4 .ValueB}} & {{delta .Delta}} \\
{{- end}}
{{- end}}
\bottomrule
\end{tabular}
\end{table}


%% ==========================================================================
%% TABLE 3: Per-Level Breakdown
%% ==========================================================================
\begin{table}[t]
\centering
\caption{Per-level performance breakdown. L1: diagnostic (identify the fault), L2: repair (diagnose and fix), L3: multi-step (cross-resource resolution). $n$ = runs per model per level.}
\label{tab:perlevel}
\small
\begin{tabular}{@{}l rr rr rr r@{}}
\toprule
 & \multicolumn{2}{c}{ESR $\uparrow$} & \multicolumn{2}{c}{TSA $\uparrow$} & \multicolumn{2}{c}{CHR $\downarrow$} & \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}
Level & \multicolumn{1}{c}{A} & \multicolumn{1}{c}{B} & \multicolumn{1}{c}{A} & \multicolumn{1}{c}{B} & \multicolumn{1}{c}{A} & \multicolumn{1}{c}{B} & $n$ \\
\midrule
{{- range .PerLevel}}
{{levelTag .Level}} & {{pct .ESRA}} & {{pct .ESRB}} & {{pct .TSAA}} & {{pct .TSAB}} & {{pct .CHRA}} & {{pct .CHRB}} & {{.RunsA}} \\
{{- end}}
\bottomrule
\end{tabular}
\end{table}


%% ==========================================================================
%% TABLE 4: Per-Task ESR — Win/Loss/Tie Summary
%% ==========================================================================
\begin{table}[t]
\centering
\caption{Per-task ESR comparison ({{shortName .ModelA}} vs.\ {{shortName .ModelB}}). A \textit{win} means model~A achieved higher ESR on that task.}
\label{tab:pertask-summary}
\small
\begin{tabular}{@{}lrrr@{}}
\toprule
 & Wins (A) & Ties & Losses (A) \\
\midrule
All tasks ($n={{len .PerTask}}$) & {{wins .PerTask}} & {{ties .PerTask}} & {{losses .PerTask}} \\
\bottomrule
\end{tabular}
\end{table}


%% ==========================================================================
%% TABLE 5: RAG Quality Metrics (task design validation)
%% ==========================================================================
\begin{table}[t]
\centering
\caption{RAG retrieval quality metrics averaged over all 60~tasks. These validate the benchmark design rather than model performance: $R@K=1.0$ by construction (all relevant documents included).}
\label{tab:rag}
\small
\begin{tabular}{@{}lrrrrr@{}}
\toprule
 & P@K & R@K & F$_1$@K & MRR & NDCG@K \\
\midrule
Benchmark & {{f3 .Raw.A.RAG.MeanPrecisionAtK}} & {{f3 .Raw.A.RAG.MeanRecallAtK}} & {{f3 .Raw.A.RAG.MeanFScoreAtK}} & {{f3 .Raw.A.RAG.MeanMRR}} & {{f3 .Raw.A.RAG.MeanNDCGAtK}} \\
\bottomrule
\end{tabular}
\end{table}


%% ==========================================================================
%% TABLE 6: Experimental Setup
%% ==========================================================================
\begin{table}[t]
\centering
\caption{Experimental configuration. Both models evaluated under identical conditions on the same hardware with deterministic sampling (temperature$=0$, seed$={{.Raw.A.Metadata.Seed}}$).}
\label{tab:setup}
\small
\begin{tabular}{@{}ll@{}}
\toprule
Parameter & Value \\
\midrule
Model A            & {{esc .ModelA}} \\
Model B            & {{esc .ModelB}} \\
Tasks              & {{.Raw.A.Metadata.TotalTasks}} (L1:20, L2:20, L3:20) \\
Runs per task      & {{.Raw.A.Metadata.RunsPerTask}} \\
Total runs / model & {{.Raw.A.Metadata.TotalRuns}} \\
Random seed        & {{.Raw.A.Metadata.Seed}} \\
Temperature        & 0 \\
Correction         & Holm--Bonferroni ($m={{len (tested .Aggregate)}}$) \\
Effect size        & Rank-biserial $r$ \\
\bottomrule
\end{tabular}
\end{table}


%% ==========================================================================
%% APPENDIX TABLE: Full Per-Task ESR
%% ==========================================================================
\begin{table*}[t]
\centering
\caption{Per-task ESR for all 60~benchmark tasks. $\Delta = \text{ESR}_A - \text{ESR}_B$; positive values favor {{shortName .ModelA}}.}
\label{tab:pertask-full}
\scriptsize
\begin{tabular}{@{}llrrr|llrrr@{}}
\toprule
Task & Lvl & A & B & $\Delta$ & Task & Lvl & A & B & $\Delta$ \\
\midrule
{{- $tasks := .PerTask}}
{{- $h := half $tasks}}
{{- range $i := seq $h}}
{{- $t := taskAt $tasks $i}}
{{- $j := add $i $h}}
{{- $t2 := taskAt $tasks $j}}
{{esc $t.TaskID}} & {{levelTag $t.Level}} & {{pct $t.ESRA}} & {{pct $t.ESRB}} & {{deltaPct $t.Delta}} & {{esc $t2.TaskID}} & {{levelTag $t2.Level}} & {{pct $t2.ESRA}} & {{pct $t2.ESRB}} & {{deltaPct $t2.Delta}} \\
{{- end}}
\bottomrule
\end{tabular}
\end{table*}
`

// RenderCompareLatex writes LaTeX tables for a compare JSON payload to w.
func RenderCompareLatex(w io.Writer, cr CompareReport) error {
	funcMap := template.FuncMap{
		"pct":       func(v float64) string { return fmt.Sprintf("%.1f", v*100) },
		"f2":        func(v float64) string { return fmt.Sprintf("%.2f", v) },
		"f3":        func(v float64) string { return fmt.Sprintf("%.3f", v) },
		"f4":        func(v float64) string { return fmt.Sprintf("%.4f", v) },
		"sci":       FmtSci,
		"delta":     FmtDelta,
		"deltaPct":  FmtDeltaPct,
		"sig":       FmtSig,
		"esc":       TexEscape,
		"shortName": ShortModelTexName,
		"levelTag":  LevelTagShort,
		"isTested":  MetricIsHolmTested,
		"add":       func(a, b int) int { return a + b },
		"half":      func(tc []TaskComparison) int { return len(tc) / 2 },
		"taskAt":    func(tc []TaskComparison, i int) TaskComparison { return tc[i] },
		"lt":        func(a, b int) bool { return a < b },
		"seq": func(n int) []int {
			s := make([]int, n)
			for i := range s {
				s[i] = i
			}
			return s
		},
		"wins":   func(tc []TaskComparison) int { return CountTaskComparisonDelta(tc, 1) },
		"ties":   func(tc []TaskComparison) int { return CountTaskComparisonDelta(tc, 0) },
		"losses": func(tc []TaskComparison) int { return CountTaskComparisonDelta(tc, -1) },
		"tested":  FilterHolmTestedMetrics,
		"scalars": FilterScalarMetrics,
	}

	tpl, err := template.New("latex").Funcs(funcMap).Parse(CompareLatexTemplate)
	if err != nil {
		return err
	}
	return tpl.Execute(w, cr)
}
